Orange_lala/Orange_lala/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oneself.urls')),
    path('', include('home.urls')),
    path('', views.homepage, name='home')
]

Orange_lala/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('home/register/', views.register, name='register'),
    path('home/login/', views.login, name='login'),
    path('home/sort/', views.sort, name='sort'),
    path('home/introduction/', views.introduction, name='introduction'),
    path('home/search/', views.search, name='search'),
    path('home/shopcart/', views.shopcart, name='shopcart'),
    path('home/pay/', views.pay, name='pay'),
    path('home/success/', views.success, name='success'),
]

Orange_lala/oneself/urls.py
from django.urls import path
from oneself import views

app_name = 'myself'

urlpatterns = [
    path('myself/', views.myself_index, name='index'),
    path('myself/myself_information/', views.myself_information, name='myself_information'),
    path('myself/myself_safety/', views.myself_safety, name='myself_safety'),
    path('myself/myself_setpay/', views.myself_setpay, name='myself_setpay'),
    path('myself/myself_password/', views.myself_password, name='myself_password'),
    path('myself/myself_bindphone/', views.myself_bindphone, name='myself_bindphone'),
    path('myself/myself_email/', views.myself_email, name='myself_email'),
    path('myself/myself_idcard/', views.myself_idcard, name='myself_idcard'),
    path('myself/myself_question/', views.myself_question, name='myself_question'),
    path('myself/address/', views.myself_address, name='address'),
    path('myself/myself_order/', views.myself_order, name='myself_order'),
    path('myself/myself_orderinfo/', views.myself_orderinfo, name='myself_orderinfo'),
    path('myself/myself_refund/', views.myself_refund, name='myself_refund'),
    path('myself/myself_logistics/', views.myself_logistics, name='myself_logistics'),
    path('myself/myself_commentlist/', views.myself_commentlist, name='myself_commentlist'),
    path('myself/myself_change/', views.myself_change, name='myself_change'),
    path('myself/myself_record/', views.myself_record, name='myself_record'),
    path('myself/myself_coupon/', views.myself_coupon, name='myself_coupon'),
    path('myself/myself_bonus/', views.myself_bonus, name='myself_bonus'),
    path('myself/myself_bill/', views.myself_bill, name='myself_bill'),
    path('myself/myself_billlist/', views.myself_billlist, name='myself_billlist'),
    path('myself/myself_collection/', views.myself_collection, name='myself_collection'),
    path('myself/myself_foot/', views.myself_foot, name='myself_foot'),
    path('myself/myself_comment/', views.myself_comment, name='myself_comment'),
    path('myself/myself_news/', views.myself_news, name='myself_news'),
    path('myself/myself_blog/', views.myself_blog, name='myself_blog'),
    ]

Orange_lala/templates/person/bill.html
<!DOCTYPE html>
<html>
    {% load static %}
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=0">

		<title>个人账单</title>

		<link href="{% static 'assets/css/admin.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'assets/css/amazeui.css' %}" rel="stylesheet" type="text/css">

		<link href="{% static 'css/personal.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'css/blstyle.css' %}" rel="stylesheet" type="text/css">
		<script src="{% static 'assets/js/jquery.min.js' %}"></script>
	</head>

	<body>
{#		<!--头 -->#}
{#		<header>#}
{#			<article>#}
{#				<div class="mt-logo">#}
{#					<!--顶部导航条 -->#}
{#					<div class="am-container header">#}
{#						<ul class="message-l">#}
{#							<div class="topMessage">#}
{#								<div class="menu-hd">#}
{#									<a href="#" target="_top" class="h">亲，请登录</a>#}
{#									<a href="#" target="_top">免费注册</a>#}
{#								</div>#}
{#							</div>#}
{#						</ul>#}
{#						<ul class="message-r">#}
{#							<div class="topMessage home">#}
{#								<div class="menu-hd"><a href="#" target="_top" class="h">商城首页</a></div>#}
{#							</div>#}
{#							<div class="topMessage my-shangcheng">#}
{#								<div class="menu-hd MyShangcheng"><a href="#" target="_top"><i class="am-icon-user am-icon-fw"></i>个人中心</a></div>#}
{#							</div>#}
{#							<div class="topMessage mini-cart">#}
{#								<div class="menu-hd"><a id="mc-menu-hd" href="#" target="_top"><i class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车</span><strong id="J_MiniCartNum" class="h">0</strong></a></div>#}
{#							</div>#}
{#							<div class="topMessage favorite">#}
{#								<div class="menu-hd"><a href="#" target="_top"><i class="am-icon-heart am-icon-fw"></i><span>收藏夹</span></a></div>#}
{#						</ul>#}
{#						</div>#}
{##}
{#						<!--悬浮搜索框-->#}
{##}
{#						<div class="nav white">#}
{#							<div class="logoBig">#}
{#								<li><img src="{% static 'images/logobig.png' %}" /></li>#}
{#							</div>#}
{##}
{#							<div class="search-bar pr">#}
{#								<a name="index_none_header_sysc" href="#"></a>#}
{#								<form>#}
{#									<input id="searchInput" name="index_none_header_sysc" type="text" placeholder="搜索" autocomplete="off">#}
{#									<input id="ai-topsearch" class="submit am-btn" value="搜索" index="1" type="submit">#}
{#								</form>#}
{#							</div>#}
{#						</div>#}
{##}
{#						<div class="clear"></div>#}
{#					</div>#}
{#				</div>#}
{#			</article>#}
{#		</header>#}
{##}
{#            <div class="nav-table">#}
{#					   <div class="long-title"><span class="all-goods">全部分类</span></div>#}
{#					   <div class="nav-cont">#}
{#							<ul>#}
{#								<li class="index"><a href="#">首页</a></li>#}
{#                                <li class="qc"><a href="#">闪购</a></li>#}
{#                                <li class="qc"><a href="#">限时抢</a></li>#}
{#                                <li class="qc"><a href="#">团购</a></li>#}
{#                                <li class="qc last"><a href="#">大包装</a></li>#}
{#							</ul>#}
{#						    <div class="nav-extra">#}
{#						    	<i class="am-icon-user-secret am-icon-md nav-user"></i><b></b>我的福利#}
{#						    	<i class="am-icon-angle-right" style="padding-left: 10px;"></i>#}
{#						    </div>#}
{#						</div>#}
{#			</div>#}
{#			<b class="line"></b>#}
        {% include 'person/top.html' %}
		<div class="center">
			<div class="col-main">
				<div class="main-wrap">

					<div class="user-bill">
						<!--标题 -->
						<div class="am-cf am-padding">
							<div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">账单</strong> / <small>Electronic&nbsp;bill</small></div>
						</div>
						<hr/>

						<div class="ebill-section">
							<div class="ebill-title-section">
								<h2 class="trade-title section-title">
                                                                                                                                     交易
                            <span class="desc">（金额单位：元）</span>
                        </h2>

								<div class=" ng-scope">
									<div class="trade-circle-select  slidedown-">
										<a href="javascript:void(0);" class="current-circle ng-binding">2015/11/01 - 2015/11/30</a>

									</div>
									<span class="title-tag"><i class="num ng-binding">12</i>月</span>
								</div>
							</div>

							<div class="module-income ng-scope">
								<div class="income-slider ">
									<div class="block-income block  fn-left">
										<h3 class="income-title block-title">
                                                                                                          支出
                                      <span class="num ng-binding">
                                              119.80
                                       </span>
                                    <span class="desc ng-binding">
                                           <a href="{% url 'myself:myself_billlist' %}">查看支出明细</a>
                                         </span>
                                             </h3>

										<div ng-class="shoppingChart" class="catatory-details  fn-hide shopping">
											<div class="catatory-chart fn-left fn-hide">
												<div class="title">类型</div>
												<ul>


												</ul>
											</div>
											<div class="catatory-detail fn-left">
												<div class="title ng-binding">
													购买商品
												</div>
												<ul>
												
													<li class="ng-scope  delete-false">

														<div class="  ng-scope">
															<a href="#" class="text fn-left " title="呢子大衣">
																<span class="emoji-span ng-binding">呢子大衣</span>
																<span class="amount fn-right ng-binding">349.00</span>
															</a>
														</div>
													</li>

													<li class="ng-scope  delete-false">

														<div class="  ng-scope">
															<a href="#" class="text fn-left " title="金士顿羊年限量版16gU盘">
																<span class="emoji-span ng-binding">金士顿羊年限量版16gU盘</span>
																<span class="amount fn-right ng-binding">39.00</span>
															</a>
														</div>
													</li>

													<li class="ng-scope  delete-false">

														<div class="  ng-scope">
															<a href="#" class="text fn-left " title="呢子大衣">
																<span class="emoji-span ng-binding">呢子大衣</span>
																<span class="amount fn-right ng-binding">349.00</span>
															</a>
														</div>
													</li>

													<li class="ng-scope  delete-false">

														<div class="  ng-scope">
															<a href="#" class="text fn-left " title="金士顿羊年限量版16gU盘">
																<span class="emoji-span ng-binding">金士顿羊年限量版16gU盘</span>
																<span class="amount fn-right ng-binding">39.00</span>
															</a>
														</div>
													</li>

													<li class="ng-scope  delete-false">

														<div class="  ng-scope">
															<a href="#" class="text fn-left " title="呢子大衣">
																<span class="emoji-span ng-binding">呢子大衣</span>
																<span class="amount fn-right ng-binding">349.00</span>
															</a>
														</div>
													</li>

													<li class="ng-scope  delete-false">

														<div class="  ng-scope">
															<a href="#" class="text fn-left " title="羊毛毡底鞋垫">
																<span class="emoji-span ng-binding">羊毛毡底鞋垫</span>
																<span class="amount fn-right ng-binding">9.90</span>
															</a>
														</div>
													</li>

												</ul>
											</div>
										</div>
									</div>
									<div class="block-expense block  fn-left">
										<div class="slide-button right"></div>
									</div>
									<div class="clear"></div>

									<!--收入-->
									<h3 class="expense income-title block-title">
                                                                                                                       收入                                                              
                                      <span class="num ng-binding">
                                              0.00
                                       </span>
                                    <span class="desc ng-binding">
                                           <a href="{% url 'myself:myself_billlist' %}">查看收入明细</a>
                                    </span>
                                </h3>
								</div>

								<!--消费走势-->
								<div class="module-consumeTrend inner-module">
									<h3 class="module-title">消费走势</h3>
									<div id="consumeTrend-chart" class="consumeTrend-chart">

									</div>
								</div>

								<!--银行卡使用情况-->

								<div class="module-card inner-module">
									<h3 class="module-title">银行卡使用情况</h3>
									<div class="card-chart valid">
										<div class="cards-carousel">
											<div class="mask">

												<div class="bac fn-left"></div>
												<div class="bank ng-binding" style="background-image: url(../images/combo.png);">中国农业银行</div>
												<div class="details">
													<a>查看详情</a>
												</div>
											</div>
										</div>
										<div class="cards-details">
											<div class="bank-name">
												<div class="name fn-left" style="background-image: url(../images/combo.png);"></div>
												<span class="close fn-right"><a>X</a></span>
											</div>
											<div class="bank-detail">
												<div class="totalin fn-left">
													<span class="fn-left">流入</span>
													<span class="amount fn-right">0.00</span>
												</div>
												<div class="totalout fn-left">
													<span class="fn-left">流出</span>
													<span class="amount fn-right">0.00</span>
												</div>
												<div class="expand fn-left">
													<span class="fn-left">支出</span>
													<span class="amount fn-right">0.00</span>
												</div>
												<div class="withdraw fn-left">
													<span class="fn-left">提现</span>
													<span class="amount fn-right">
							                                0.00
                            						</span>
												</div>
												<div class="recharge fn-left">
													<span class="fn-left">充值</span>
													<span class="amount fn-right">
                                                            0.00
                            						</span>
												</div>

												<div class="refund fn-left">
													<span class="fn-left">银行卡退款</span>
													<span class="amount fn-right ">0.00</span>
												</div>
											</div>
										</div>
									</div>
								</div>

								<script>
									$(document).ready(function (ev) {
								
									    $('.cards-carousel .details').on('click', function (ev) {
								             $('.cards-details').css("display","block");
								             $('.cards-carousel').css("display","none");								 
									    });									   									    
								
									    $('.cards-details .close').on('click', function (ev) {
								             $('.cards-details').css("display","none");
								             $('.cards-carousel').css("display","block");								 
									    });									    
									    									   								    
									});
								</script>

							</div>

						</div>

					</div>
				</div>
				<!--底部-->
				<div class="footer">
					<div class="footer-hd">
						<p>
							<a href="#">恒望科技</a>
							<b>|</b>
							<a href="#">商城首页</a>
							<b>|</b>
							<a href="#">支付宝</a>
							<b>|</b>
							<a href="#">物流</a>
						</p>
					</div>
					<div class="footer-bd">
						<p>
							<a href="#">关于恒望</a>
							<a href="#">合作伙伴</a>
							<a href="#">联系我们</a>
							<a href="#">网站地图</a>
							<em>© 2015-2025 Hengwang.com 版权所有</em>
						</p>
					</div>
				</div>

			</div>

			<aside class="menu">
				<ul>
					<li class="person active">
						<a href="{% url 'myself:index' %}">个人中心</a>
					</li>
					<li class="person">
						<a href="#">个人资料</a>
						<ul>
							<li> <a href="{% url 'myself:myself_information' %}">个人信息</a></li>
							<li> <a href="{% url 'myself:myself_safety' %}">安全设置</a></li>
							<li> <a href="{% url 'myself:address' %}">收货地址</a></li>
						</ul>
					</li>
					<li class="person">
						<a href="#">我的交易</a>
						<ul>
							<li><a href="{% url 'myself:myself_order' %}">订单管理</a></li>
							<li> <a href="{% url 'myself:myself_change' %}">退款售后</a></li>
						</ul>
					</li>
					<li class="person">
						<a href="#">我的资产</a>
						<ul>
							<li> <a href="{% url 'myself:myself_coupon' %}">优惠券 </a></li>
							<li> <a href="{% url 'myself:myself_bonus' %}">红包</a></li>
							<li> <a href="{% url 'myself:myself_bill' %}">账单明细</a></li>
						</ul>
					</li>

					<li class="person">
						<a href="#">我的小窝</a>
						<ul>
							<li> <a href="{% url 'myself:myself_collection' %}">收藏</a></li>
							<li> <a href="{% url 'myself:myself_foot' %}">足迹</a></li>
							<li> <a href="{% url 'myself:myself_comment' %}">评价</a></li>
							<li> <a href="{% url 'myself:myself_news' %}">消息</a></li>
						</ul>
					</li>

				</ul>

			</aside>
		</div>

	</body>

</html>

Orange_lala/templates/person/safety.html
<!DOCTYPE html>
<html>
    {% load static %}
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=0">

		<title>安全设置</title>

		<link href="{% static 'assets/css/admin.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'assets/css/amazeui.css' %}" rel="stylesheet" type="text/css">

		<link href="{% static 'css/personal.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'css/infstyle.css' %}" rel="stylesheet" type="text/css">
	</head>

	<body>
{#		<!--头 -->#}
{#		<header>#}
{#			<article>#}
{#				<div class="mt-logo">#}
{#					<!--顶部导航条 -->#}
{#					<div class="am-container header">#}
{#						<ul class="message-l">#}
{#							<div class="topMessage">#}
{#								<div class="menu-hd">#}
{#									<a href="#" target="_top" class="h">亲，请登录</a>#}
{#									<a href="#" target="_top">免费注册</a>#}
{#								</div>#}
{#							</div>#}
{#						</ul>#}
{#						<ul class="message-r">#}
{#							<div class="topMessage home">#}
{#								<div class="menu-hd"><a href="#" target="_top" class="h">商城首页</a></div>#}
{#							</div>#}
{#							<div class="topMessage my-shangcheng">#}
{#								<div class="menu-hd MyShangcheng"><a href="#" target="_top"><i class="am-icon-user am-icon-fw"></i>个人中心</a></div>#}
{#							</div>#}
{#							<div class="topMessage mini-cart">#}
{#								<div class="menu-hd"><a id="mc-menu-hd" href="#" target="_top"><i class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车</span><strong id="J_MiniCartNum" class="h">0</strong></a></div>#}
{#							</div>#}
{#							<div class="topMessage favorite">#}
{#								<div class="menu-hd"><a href="#" target="_top"><i class="am-icon-heart am-icon-fw"></i><span>收藏夹</span></a></div>#}
{#						</ul>#}
{#						</div>#}
{##}
{#						<!--悬浮搜索框-->#}
{##}
{#						<div class="nav white">#}
{#							<div class="logoBig">#}
{#								<li><img src="{% static 'images/logobig.png' %}" /></li>#}
{#							</div>#}
{##}
{#							<div class="search-bar pr">#}
{#								<a name="index_none_header_sysc" href="#"></a>#}
{#								<form>#}
{#									<input id="searchInput" name="index_none_header_sysc" type="text" placeholder="搜索" autocomplete="off">#}
{#									<input id="ai-topsearch" class="submit am-btn" value="搜索" index="1" type="submit">#}
{#								</form>#}
{#							</div>#}
{#						</div>#}
{##}
{#						<div class="clear"></div>#}
{#					</div>#}
{#				</div>#}
{#			</article>#}
{#		</header>#}
{#            <div class="nav-table">#}
{#					   <div class="long-title"><span class="all-goods">全部分类</span></div>#}
{#					   <div class="nav-cont">#}
{#							<ul>#}
{#								<li class="index"><a href="#">首页</a></li>#}
{#                                <li class="qc"><a href="#">闪购</a></li>#}
{#                                <li class="qc"><a href="#">限时抢</a></li>#}
{#                                <li class="qc"><a href="#">团购</a></li>#}
{#                                <li class="qc last"><a href="#">大包装</a></li>#}
{#							</ul>#}
{#						    <div class="nav-extra">#}
{#						    	<i class="am-icon-user-secret am-icon-md nav-user"></i><b></b>我的福利#}
{#						    	<i class="am-icon-angle-right" style="padding-left: 10px;"></i>#}
{#						    </div>#}
{#						</div>#}
{#			</div>#}
{#			<b class="line"></b>#}
        {% include 'person/top.html' %}
		<div class="center">
			<div class="col-main">
				<div class="main-wrap">

					<!--标题 -->
					<div class="user-safety">
						<div class="am-cf am-padding">
							<div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">账户安全</strong> / <small>Set&nbsp;up&nbsp;Safety</small></div>
						</div>
						<hr/>

						<!--头像 -->
						<div class="user-infoPic">

							<div class="filePic">
								<img class="am-circle am-img-thumbnail" src="{% static 'images/getAvatar.do.jpg' %}" alt="" />
							</div>

							<p class="am-form-help">头像</p>

							<div class="info-m">
								<div><b>用户名：<i>小叮当</i></b></div>
								<div class="u-level">
									<span class="rank r2">
							             <s class="vip1"></s><a class="classes" href="#">铜牌会员</a>
						            </span>
								</div>
								<div class="u-safety">
									<a href="safety.html">
									 账户安全
									<span class="u-profile"><i class="bc_ee0000" style="width: 60px;" width="0">60分</i></span>
									</a>
								</div>
							</div>
						</div>

						<div class="check">
							<ul>
								<li>
									<i class="i-safety-lock"></i>
									<div class="m-left">
										<div class="fore1">登录密码</div>
										<div class="fore2"><small>为保证您购物安全，建议您定期更改密码以保护账户安全。</small></div>
									</div>
									<div class="fore3">
										<a href="{% url 'myself:myself_password' %}">
											<div class="am-btn am-btn-secondary">修改</div>
										</a>
									</div>
								</li>
								<li>
									<i class="i-safety-wallet"></i>
									<div class="m-left">
										<div class="fore1">支付密码</div>
										<div class="fore2"><small>启用支付密码功能，为您资产账户安全加把锁。</small></div>
									</div>
									<div class="fore3">
										<a href="{% url 'myself:myself_setpay' %}">
											<div class="am-btn am-btn-secondary">立即启用</div>
										</a>
									</div>
								</li>
								<li>
									<i class="i-safety-iphone"></i>
									<div class="m-left">
										<div class="fore1">手机验证</div>
										<div class="fore2"><small>您验证的手机：186XXXXXXXX 若已丢失或停用，请立即更换</small></div>
									</div>
									<div class="fore3">
										<a href="{% url 'myself:myself_bindphone' %}">
											<div class="am-btn am-btn-secondary">换绑</div>
										</a>
									</div>
								</li>
								<li>
									<i class="i-safety-mail"></i>
									<div class="m-left">
										<div class="fore1">邮箱验证</div>
										<div class="fore2"><small>您验证的邮箱：5831XXX@qq.com 可用于快速找回登录密码</small></div>
									</div>
									<div class="fore3">
										<a href="{% url 'myself:myself_email' %}">
											<div class="am-btn am-btn-secondary">换绑</div>
										</a>
									</div>
								</li>
								<li>
									<i class="i-safety-idcard"></i>
									<div class="m-left">
										<div class="fore1">实名认证</div>
										<div class="fore2"><small>用于提升账号的安全性和信任级别，认证后不能修改认证信息。</small></div>
									</div>
									<div class="fore3">
										<a href="{% url 'myself:myself_idcard' %}">
											<div class="am-btn am-btn-secondary">认证</div>
										</a>
									</div>
								</li>
								<li>
									<i class="i-safety-security"></i>
									<div class="m-left">
										<div class="fore1">安全问题</div>
										<div class="fore2"><small>保护账户安全，验证您身份的工具之一。</small></div>
									</div>
									<div class="fore3">
										<a href="{% url 'myself:myself_question' %}">
											<div class="am-btn am-btn-secondary">认证</div>
										</a>
									</div>
								</li>
							</ul>
						</div>

					</div>
				</div>
				<!--底部-->
				<div class="footer">
					<div class="footer-hd">
						<p>
							<a href="#">恒望科技</a>
							<b>|</b>
							<a href="#">商城首页</a>
							<b>|</b>
							<a href="#">支付宝</a>
							<b>|</b>
							<a href="#">物流</a>
						</p>
					</div>
					<div class="footer-bd">
						<p>
							<a href="#">关于恒望</a>
							<a href="#">合作伙伴</a>
							<a href="#">联系我们</a>
							<a href="#">网站地图</a>
							<em>© 2015-2025 Hengwang.com 版权所有</em>
						</p>
					</div>
				</div>
			</div>

			<aside class="menu">
				<ul>
					<li class="person active">
						<a href="{% url 'myself:index' %}">个人中心</a>
					</li>
					<li class="person">
						<a href="#">个人资料</a>
						<ul>
							<li> <a href="{% url 'myself:myself_information' %}">个人信息</a></li>
							<li> <a href="{% url 'myself:myself_safety' %}">安全设置</a></li>
							<li> <a href="{% url 'myself:address' %}">收货地址</a></li>
						</ul>
					</li>
					<li class="person">
						<a href="#">我的交易</a>
						<ul>
							<li><a href="{% url 'myself:myself_order' %}">订单管理</a></li>
							<li> <a href="{% url 'myself:myself_change' %}">退款售后</a></li>
						</ul>
					</li>
					<li class="person">
						<a href="#">我的资产</a>
						<ul>
							<li> <a href="{% url 'myself:myself_coupon' %}">优惠券 </a></li>
							<li> <a href="{% url 'myself:myself_bonus' %}">红包</a></li>
							<li> <a href="{% url 'myself:myself_bill' %}">账单明细</a></li>
						</ul>
					</li>

					<li class="person">
						<a href="#">我的小窝</a>
						<ul>
							<li> <a href="{% url 'myself:myself_collection' %}">收藏</a></li>
							<li> <a href="{% url 'myself:myself_foot' %}">足迹</a></li>
							<li> <a href="{% url 'myself:myself_comment' %}">评价</a></li>
							<li> <a href="{% url 'myself:myself_news' %}">消息</a></li>
						</ul>
					</li>

				</ul>

			</aside>
		</div>

	</body>

</html>

Orange_lala/templates/person/top.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
{#    <link href="{% static 'assets/css/admin.css' %}" rel="stylesheet" type="text/css">#}
{#    <link href="{% static 'assets/css/amazeui.css' %}" rel="stylesheet" type="text/css">#}
{#    <link href="{% static 'css/personal.css' %}" rel="stylesheet" type="text/css">#}
{#    <link href="{% static 'css/systyle.css' %}" rel="stylesheet" type="text/css">#}
</head>
<body>
<header>
			<article>
				<div class="mt-logo">
					<!--顶部导航条 -->
					<div class="am-container header">
						<ul class="message-l">
							<div class="topMessage">
								<div class="menu-hd">
									<a href="#" target="_top" class="h">亲，请登录</a>
									<a href="#" target="_top">免费注册</a>
								</div>
							</div>
						</ul>
						<ul class="message-r">
							<div class="topMessage home">
								<div class="menu-hd"><a href="{% url 'home:homepage' %}" target="_top" class="h">商城首页</a></div>
							</div>
							<div class="topMessage my-shangcheng">
								<div class="menu-hd MyShangcheng"><a href="{% url 'myself:index' %}" target="_top"><i class="am-icon-user am-icon-fw"></i>个人中心</a></div>
							</div>
							<div class="topMessage mini-cart">
								<div class="menu-hd"><a id="mc-menu-hd" href="{% url 'home:shopcart' %}" target="_top"><i class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车</span><strong id="J_MiniCartNum" class="h">0</strong></a></div>
							</div>
							<div class="topMessage favorite">
								<div class="menu-hd"><a href="{% url 'myself:myself_collection' %}" target="_top"><i class="am-icon-heart am-icon-fw"></i><span>收藏夹</span></a></div>
                            </div>

						</ul>
						</div>

						<!--悬浮搜索框-->

						<div class="nav white">
							<div class="logoBig">
								<li><img src="{% static 'images/logobig.png' %}" /></li>
							</div>

							<div class="search-bar pr">
								<a name="index_none_header_sysc" href="#"></a>
								<form>
									<input id="searchInput" name="index_none_header_sysc" type="text" placeholder="输入关键词" autocomplete="off">
									<input id="ai-topsearch" class="submit am-btn" value="个人信息查询" index="1" type="submit">
								</form>
							</div>

						</div>

						<div class="clear"></div>
					</div>
				</div>
			</article>
		</header>
            <div class="nav-table">
{#					   <div class="long-title"><span class="all-goods"></span></div>#}
					   <div class="nav-cont">
{#							<ul>#}
{#								<li class="index"><a href="#"></a></li>#}
{#                                <li class="qc"><a href="#"></a></li>#}
{#                                <li class="qc"><a href="#"></a></li>#}
{#                                <li class="qc"><a href="#"></a></li>#}
{#                                <li class="qc last"><a href="#">大包装</a></li>#}
{#							</ul>#}
{#                           <span>欢迎</span>#}
						    <div class="nav-extra">
						    	<i class="am-icon-user-secret am-icon-md nav-user"></i><b></b>我的福利
						    	<i class="am-icon-angle-right" style="padding-left: 10px;"></i>
						    </div>
						</div>
			</div>
<b class="line"></b>

</body>
</html>