Orange_lala/Orange_lala/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oneself.urls')),
    path('', include('home.urls')),
    path('', views.homepage, name='home')
]

Orange_lala/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('home/', views.homepage, name='homepage'),
    path('home/register/', views.register, name='register'),
    path('home/login/', views.login, name='login'),
    path('home/sort/', views.sort, name='sort'),
    path('home/introduction/', views.introduction, name='introduction'),
    path('home/search/', views.search, name='search'),
    path('home/shopcart/', views.shopcart, name='shopcart'),
    path('home/pay/', views.pay, name='pay'),
    path('home/success/', views.success, name='success'),
]

Orange_lala/home/models.py
from django.db import models

# Create your models here.

Orange_lala/templates/home/login.html
{% load static %}
<!DOCTYPE html>
<html>

	<head lang="en">
		<meta charset="UTF-8">
		<title>登录</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="format-detection" content="telephone=no">
		<meta name="renderer" content="webkit">
		<meta http-equiv="Cache-Control" content="no-siteapp" />

		<link rel="stylesheet" href="{% static 'assets/css/amazeui.css' %}" />
		<link href="{% static 'css/dlstyle.css' %}" rel="stylesheet" type="text/css">
	</head>

	<body>

		<div class="login-boxtitle"> {# 这里的home应为home2 #}
			<a href="{% url 'home:homepage' %}"><img alt="logo" src="{% static 'images/logobig.png' %}" /></a>
		</div>

		<div class="login-banner">
			<div class="login-main">
				<div class="login-banner-bg"><span></span><img src="{% static 'images/big.jpg' %}" /></div>
				<div class="login-box">

							<h3 class="title">登录商城</h3>

							<div class="clear"></div>
						
						<div class="login-form">
						  <form>
                              <div class="user-name">
                                  <label for="user"><i class="am-icon-user"></i></label>
                                  <input type="text" name="" id="user" placeholder="邮箱/手机/用户名">
                              </div>
                              <div class="user-pass">
                                  <label for="password"><i class="am-icon-lock"></i></label>
                                  <input type="password" name="" id="password" placeholder="请输入密码">
                              </div>
                              <div style="width: 300px;height: 44px;background-color: #fff;">
{#                                  <label for="remember-me">#}
                                      <input id="remember-me" type="checkbox" style="width:18px;height: 36px;margin: 0 15px"><p style="margin: -35px 45px;">记住密码</p>
{#                                  </label>#}
                                  <a href="#" class="am-fr">忘记密码</a>
                                  <a href="{% url 'home:register' %}" class="zcnext am-fr am-btn-default">注册</a>
                                  <br />
                              </div>
                              <div class="am-cf">
                                  <input type="submit" name="" value="登 录" class="am-btn am-btn-primary am-btn-sm">
                              </div>
                          </form>
                        </div>

						<div class="partner">		
								<h3>合作账号</h3>
							<div class="am-btn-group">
								<li><a href="#"><i class="am-icon-qq am-icon-sm"></i><span>QQ登录</span></a></li>
								<li><a href="#"><i class="am-icon-weibo am-icon-sm"></i><span>微博登录</span> </a></li>
								<li><a href="#"><i class="am-icon-weixin am-icon-sm"></i><span>微信登录</span> </a></li>
							</div>
						</div>	

				</div>
			</div>
		</div>


					<div class="footer ">
						<div class="footer-hd ">
							<p>
								<a href="#">恒望科技</a>
								<b>|</b>
								<a href="{% url 'home:homepage' %}">商城首页</a>
								<b>|</b>
								<a href="#">支付宝</a>
								<b>|</b>
								<a href="#">物流</a>
							</p>
						</div>
						<div class="footer-bd ">
							<p>
								<a href="#">关于恒望</a>
								<a href="#">合作伙伴</a>
								<a href="#">联系我们</a>
								<a href="#">网站地图</a>
								<em>© 2015-2025 Hengwang.com 版权所有</em>
							</p>
						</div>
					</div>
	</body>

</html>

Orange_lala/templates/home/register.html
{% load static %}
<!DOCTYPE html>
<html>

	<head lang="en">
		<meta charset="UTF-8">
		<title>注册</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="format-detection" content="telephone=no">
		<meta name="renderer" content="webkit">
		<meta http-equiv="Cache-Control" content="no-siteapp" />

		<link rel="stylesheet" href="{% static 'assets/css/amazeui.min.css' %}" />
		<link href="{% static 'css/dlstyle.css' %}" rel="stylesheet" type="text/css">
		<script src="{% static 'assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'assets/js/amazeui.min.js' %}"></script>

	</head>

	<body>

		<div class="login-boxtitle">
			<a href="{% url 'home:homepage' %}"><img alt="" src="{% static 'images/logobig.png' %}" /></a>
		</div>

		<div class="res-banner">
			<div class="res-main">
				<div class="login-banner-bg"><span></span><img src="{% static 'images/big.jpg' %}" /></div>
				<div class="login-box">

						<div class="am-tabs" id="doc-my-tabs">
							<ul class="am-tabs-nav am-nav am-nav-tabs am-nav-justify">
								<li class="am-active"><a href="">邮箱注册</a></li>
								<li><a href="">手机号注册</a></li>
							</ul>

							<div class="am-tabs-bd">
								<div class="am-tab-panel am-active">
									<form method="post" action="#">
                                        {% csrf_token %}
                                        <div class="user-email">
                                            <label for="email"><i class="am-icon-envelope-o"></i></label>
                                            <input type="email" name="" id="email" placeholder="请输入邮箱账号" class="aa1">
                                        </div>
                                        <div class="user-pass">
                                            <label for="password"><i class="am-icon-lock"></i></label>
                                            <input type="password" name="" id="password" placeholder="设置密码" class="aa2">
                                        </div>
                                        <div class="user-pass">
                                            <label for="passwordRepeat"><i class="am-icon-lock"></i></label>
                                            <input type="password" name="" id="passwordRepeat" placeholder="确认密码" class="aa3">
                                        </div>
                                        <div style="width: 300px;height: 44px;background-color: #fff;">
                                          <input type="checkbox" style="width:20px;height: 39px;margin: 0 15px"><p style="margin: -36px 54px">点击同意商城《服务协议》</p>
                                        </div>
                                        <div class="am-cf">
                                            <input type="submit" name="" value="注册" class="am-btn am-btn-primary am-btn-sm am-fl" id="sub">
                                        </div>
                                    </form>
                            </div>

								<div class="am-tab-panel">
									<form method="post">
                                        <div class="user-phone">
                                            <label for="phone"><i class="am-icon-mobile-phone am-icon-md"></i></label>
                                            <input type="tel" name="" id="phone" placeholder="请输入手机号">
                                        </div>
                                        <div class="verification">
                                            <label for="code"><i class="am-icon-code-fork"></i></label>
                                            <input type="tel" name="" id="code" placeholder="请输入验证码">
                                            <a class="btn" href="javascript:void(0);" onclick="sendMobileCode();" id="sendMobileCode">
                                                <span id="dyMobileButton">获取</span></a>
                                        </div>
                                        <div class="user-pass">
                                            <label for="password"><i class="am-icon-lock"></i></label>
                                            <input type="password" name="" id="password" placeholder="设置密码">
                                        </div>
                                        <div class="user-pass">
                                            <label for="passwordRepeat"><i class="am-icon-lock"></i></label>
                                            <input type="password" name="" id="passwordRepeat" placeholder="确认密码">
                                        </div>
                                        <div style="width: 300px;height: 44px;background-color: #fff;">
{#                                            <label for="reader-me">#}
                                                <input id="reader-me" type="checkbox" style="width:19px;height: 42px;margin: 0 15px"> <p style="margin: -36px 54px">点击同意商城《服务协议》</p>
{#                                            </label>#}
                                        </div>
                                        <div class="am-cf">
                                            <input type="submit" name="" value="注册" class="am-btn am-btn-primary am-btn-sm am-fl">
                                        </div>
                                    </form>

									<hr>
								</div>

								<script>
									$(function() {
									    $('#doc-my-tabs').tabs();
									  })
								</script>

							</div>
						</div>

				</div>
			</div>
			
					<div class="footer ">
						<div class="footer-hd ">
							<p>
								<a href="#">恒望科技</a>
								<b>|</b>
								<a href="{% url 'home:homepage' %}">商城首页</a>
								<b>|</b>
								<a href="#">支付宝</a>
								<b>|</b>
								<a href="#">物流</a>
							</p>
						</div>
						<div class="footer-bd ">
							<p>
								<a href="#">关于恒望</a>
								<a href="#">合作伙伴</a>
								<a href="#">联系我们</a>
								<a href="#">网站地图</a>
								<em>© 2015-2025 Hengwang.com 版权所有</em>
							</p>
						</div>
					</div>
	</body>

</html>

Orange_lala/templates/home/success.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>付款成功页面</title>
<link rel="stylesheet"  type="text/css" href="{% static '' %}assets/css/amazeui.css"/>
<link href="{% static '' %}assets/css/admin.css" rel="stylesheet" type="text/css">
<link href="{% static '' %}basic/css/demo.css" rel="stylesheet" type="text/css" />

<link href="{% static '' %}css/sustyle.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="{% static '' %}basic/js/jquery-1.7.min.js"></script>

</head>

<body>


<!--顶部导航条 -->
<div class="am-container header">
  <ul class="message-l">
    <div class="topMessage">
     <div class="menu-hd">
       <a href="#" target="_top" class="h">亲，请登录</a>
       <a href="#" target="_top">免费注册</a>
     </div></div>
  </ul>
  <ul class="message-r">
    <div class="topMessage home"><div class="menu-hd"><a href="#" target="_top" class="h">商城首页</a></div></div>
    <div class="topMessage my-shangcheng"><div class="menu-hd MyShangcheng"><a href="#" target="_top"><i class="am-icon-user am-icon-fw"></i>个人中心</a></div></div>
    <div class="topMessage mini-cart"><div class="menu-hd"><a id="mc-menu-hd" href="#" target="_top"><i class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车</span><strong id="J_MiniCartNum" class="h">0</strong></a></div></div>
    <div class="topMessage favorite"><div class="menu-hd"><a href="#" target="_top"><i class="am-icon-heart am-icon-fw"></i><span>收藏夹</span></a></div>
  </ul>
</div>

<!--悬浮搜索框-->

<div class="nav white">
	<div class="logo"><img src="{% static '' %}images/logo.png" /></div>
    <div class="logoBig">
      <li><img src="{% static '' %}images/logobig.png" /></li>
    </div>
    
    <div class="search-bar pr">
        <a name="index_none_header_sysc" href="#"></a>       
        <form>
        <input id="searchInput" name="index_none_header_sysc" type="text" placeholder="搜索" autocomplete="off">
        <input id="ai-topsearch" class="submit" value="搜索" index="1" type="submit"></form>
    </div>     
</div>

<div class="clear"></div>



<div class="take-delivery">
 <div class="status">
   <h2>您已成功付款</h2>
   <div class="successInfo">
     <ul>
       <li>付款金额<em>¥9.90</em></li>
       <div class="user-info">
         <p>收货人：艾迪</p>
         <p>联系电话：15871145629</p>
         <p>收货地址：湖北省 武汉市 武昌区 东湖路75号众环大厦</p>
       </div>
             请认真核对您的收货信息，如有错误请联系客服
                               
     </ul>
     <div class="option">
       <span class="info">您可以</span>
        <a href="../person/order.html" class="J_MakePoint">查看<span>已买到的宝贝</span></a>
        <a href="../person/orderinfo.html" class="J_MakePoint">查看<span>交易详情</span></a>
     </div>
    </div>
  </div>
</div>


<div class="footer" >
 <div class="footer-hd">
 <p>
 <a href="#">恒望科技</a>
 <b>|</b>
 <a href="#">商城首页</a>
 <b>|</b>
 <a href="#">支付宝</a>
 <b>|</b>
 <a href="#">物流</a>
 </p>
 </div>
 <div class="footer-bd">
 <p>
 <a href="#">关于恒望</a>
 <a href="#">合作伙伴</a>
 <a href="#">联系我们</a>
 <a href="#">网站地图</a>
 <em>© 2015-2025 Hengwang.com 版权所有</em>
 </p>
 </div>
</div>


</body>
</html>